<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>GeneratorAnkiet</title>
  <link rel="stylesheet" type="text/css" media="screen"
   href="styles/style.css"/>
  <?= $this->placeholder('js') ?>
</head>
<body>
    <div id="search">
        <div id="popup">
        <div style="text-align:right;"><image src="images/menu.png"/></div>
        <?= $this->placeholder('menu') ?>
        </div>
    </div>
<div>
    
<?= $this->layout()->content ?>
    
</div>
</body>
</html>

