<?php
 $this->placeholder('js')->captureStart() ?>
<script type="text/javascript">
<!--
function dodaj_element(kontener)
{
	var option = document.createElement('input');
	option.setAttribute('type', 'text');
	option.setAttribute('name', 'option[]');
	option.style.display = "block";
	var kontener = document.getElementById(kontener);
	kontener.appendChild(option);
}
//-->
</script>
<?php $this->placeholder('js')->captureEnd() ?>
<form action="" method="post">
    <?= $this->element->question ?>
    <?= $this->element->class ?>
    <?= $this->element->add ?>
    <div id="options">
        <input type="text" name="option[]" /><br/>
    </div>
        <?= $this->element->submit ?>
</form>
